type Role =
  | 'ADMIN'
  | 'ARCHITECT'
  | 'CARPENTER'
  | 'CONSTRUCTIONCOMPANY'
  | 'CUSTOMER'
  | 'ELECTRICIAN'
  | 'INTERIORDESIGNER'
  | 'LANDSCAPEARCHITECT'
  | 'MASONWORKER'
  | 'PAINTER'
  | 'RENTER'
  | 'RETAILSTORE'
  | 'USER';
